# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eb48a1c12a0b560226753842fde26871c59f53fd00f6cfc9f506b6aaad5655440a074e767ef227285647e041cf3cde0eb476e9463e77a03c5659d65067663f7

test:
  secret_key_base: ab080faa2e4c9ccd5f2eb7e9d203910f7bbcde9abb756994efefee3a89601537229f6da513aa5542c15e426455d89179b9e0c44294123bf33f12ee9640ba4f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
